name: Build All Platforms

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "build"
  buildLinux:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.3.7
      # Runs a set of commands using the runners shell
      - name: install libvlc
        run: |
            sudo apt-get install vlc libvlc-dev libvlccore-dev vlc-bin
      - name: Install libraries
        run: |
          haxelib setup ~/haxelib
          haxelib install hxcpp > /dev/null
          haxelib install hxpkg
          haxelib run hxpkg install
      - name: Compile
        run: haxelib run lime build Project.xml linux -D ${{ inputs.buildFlags }}
      - name: Publish Artifact
        uses: actions/upload-artifact@main
        with:
          name: nmv-linux
          path: 'export/release/linux/bin' 
  buildWindows:
    runs-on: windows-latest
    
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2.3.0

      - uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.3.7
      # Runs a set of commands using the runners shell
      - name: Install libraries
        run: |
          haxelib setup C:/haxelib
          haxelib install hxcpp > nul
          haxelib install hxpkg
          haxelib run hxpkg install
      - name: Compile
        run: haxelib run lime build windows -D ${{ inputs.buildFlags }}
      - name: Publish Artifact
        uses: actions/upload-artifact@main
        with:
          name: nmv-windows
          path: export/release/windows/bin
  buildMacIntel:
    runs-on: macos-15

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@main

      - uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.3.7
      # Runs a set of commands using the runners shell
      - name: Install libraries
        run: |
          haxelib setup ~/haxelib
          haxelib install hxcpp > /dev/null --quiet
          haxelib install hxpkg
          haxelib run hxpkg install
      - name: Compile
        run: |
          haxelib run lime build mac -64 -D ${{ inputs.buildFlags || 'commit' }} -D HXCPP_M64
      - name: Publish Artifact
        uses: actions/upload-artifact@main
        with:
          name: nmv-macIntel
          path: export/release/macos/bin

  buildMacArm:
    runs-on: macos-15

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@main

      - uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.3.7
      # Runs a set of commands using the runners shell
      - name: Install libraries
        run: |
          haxelib setup ~/haxelib
          haxelib install hxcpp > /dev/null --quiet
          haxelib install hxpkg
          haxelib run hxpkg install
      - name: Compile
        run: |
          haxelib run lime build mac -arm64 -D ${{ inputs.buildFlags }} -D HXCPP_ARM64
      - name: Publish Artifact
        uses: actions/upload-artifact@main
        with:
          name: nmv-macArm
          path: export/release/macos/bin
  ios:
    name: iOS Build

    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4

      - name: Setup Haxe
        uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.3.7

      # Runs a set of commands using the runners shell
      - name: Install libraries
        run: |
          haxelib setup ~/haxelib
          haxelib install hxcpp > /dev/null --quiet
          haxelib install hxpkg
          haxelib run hxpkg install

      - name: Patch Lime for iOS 17+
        run: |
          sed -i '' 's/return systemInfo.machine;/return strdup(systemInfo.machine);/' $(haxelib path lime | head -n 1)/project/src/ios/System.mm
          sed -i '' 's/UTF8String]/UTF8String] copy]/' $(haxelib path lime | head -n 1)/project/src/ios/System.mm

      - name: Build iOS
        run: haxelib run lime build ios -release -Dsource-header

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: iOS-Build
          path: export/release/ios/build

  android:
    name: Android Build

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Haxe
        uses: krdlab/setup-haxe@v1
        with:
          haxe-version: 4.3.7

      # Runs a set of commands using the runners shell
      - name: Install libraries
        run: |
          haxelib setup ~/haxelib
          haxelib install hxcpp > /dev/null --quiet
          haxelib install hxpkg
          haxelib run hxpkg install

      - name: Install Android SDK/NDK
        uses: android-actions/setup-android@v3

      - name: Install NDK 25.2
        run: sdkmanager "ndk;25.2.9519653"

      - name: Build Android
        run: haxelib run lime build android -release

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Android-Build
          path: export/release/android/bin
